locals {
  name = "${var.name_prefix}-${var.env}"

  labels = {
    env     = var.env
    project = var.name_prefix
  }
}

module "project_services" {
  source = "./modules/project-services"

  project_id = var.project_id
  services = [
    "compute.googleapis.com",
    "container.googleapis.com",
    "sqladmin.googleapis.com",
    "secretmanager.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "artifactregistry.googleapis.com",
    "servicenetworking.googleapis.com", # private IPs for Cloud SQL / Memorystore
    "redis.googleapis.com",
  ]
}

module "network" {
  source = "./modules/network"

  name   = local.name
  region = var.region

  depends_on = [module.project_services]
}

# Least privilege for nodes, instead of the default Compute Engine account.
module "node_service_account" {
  source = "./modules/service-account"

  project_id   = var.project_id
  account_id   = "${local.name}-gke-node"
  display_name = "GKE node pool"
  # Registry access is granted per-repository below, not project-wide.
  project_roles = [
    "roles/logging.logWriter",
    "roles/monitoring.metricWriter",
    "roles/monitoring.viewer",
  ]

  depends_on = [module.project_services]
}

module "artifact_registry" {
  source = "./modules/artifact-registry"

  project_id    = var.project_id
  location      = var.region
  repository_id = local.name
  description   = "Container images for ${local.name}"
  format        = "DOCKER"
  labels        = local.labels

  readers = [module.node_service_account.member]

  depends_on = [module.project_services]
}

module "gke" {
  source = "./modules/gke"

  project_id = var.project_id
  name       = local.name
  location   = var.zone # zonal: one free cluster per billing account

  network_id          = module.network.network_id
  subnet_id           = module.network.subnet_id
  pods_range_name     = module.network.pods_range_name
  services_range_name = module.network.services_range_name

  node_service_account    = module.node_service_account.email
  master_authorized_cidrs = var.master_authorized_cidrs
  machine_type            = var.node_machine_type
  node_count              = var.node_count
  node_labels             = local.labels
  resource_labels         = local.labels
}

module "cloud_sql" {
  source = "./modules/cloud-sql"

  project_id = var.project_id
  name       = local.name
  region     = var.region
  tier       = var.db_tier
  databases  = ["litellm", "langfuse"]
  user_name  = "litellm"

  # Private IP on the cluster VPC; the Helm chart connects to it directly.
  private_network  = module.network.network_id
  enable_public_ip = false

  # module.network carries the Private Services Access peering, which must
  # exist before an instance can be given a private IP.
  depends_on = [module.project_services, module.network]
}

module "memorystore" {
  source = "./modules/memorystore"

  project_id         = var.project_id
  name               = local.name
  region             = var.region
  authorized_network = module.network.network_id
  tier               = var.redis_tier
  memory_size_gb     = var.redis_memory_gb
  labels             = local.labels

  depends_on = [module.project_services, module.network]
}

# LiteLLM reaches Cloud SQL through the Auth Proxy sidecar, authenticating as
# this account via Workload Identity. No key file is ever created.
module "litellm_service_account" {
  source = "./modules/service-account"

  project_id    = var.project_id
  account_id    = "${local.name}-litellm"
  display_name  = "LiteLLM gateway"
  project_roles = ["roles/cloudsql.client"]

  workload_identity_users = ["${var.litellm_namespace}/${var.litellm_ksa}"]

  depends_on = [module.project_services]
}

resource "random_password" "litellm_master_key" {
  length  = 40
  special = false
}

resource "random_password" "litellm_salt_key" {
  length  = 40
  special = false
}

# Keys this project issues to itself, rather than receiving from a provider:
# LiteLLM presents them to the RunPod backends, and vLLM is started with the
# same value. Generated so nothing has to be invented by hand; overridable by
# adding a newer version to the secret, since every consumer reads "latest" and
# Terraform only owns the version it created.
resource "random_password" "vllm_api_key" {
  length  = 40
  special = false
}

resource "random_password" "embedding_api_key" {
  length  = 40
  special = false
}

resource "random_password" "langfuse_secret" {
  length  = 40
  special = false
}

module "secrets" {
  source = "./modules/secrets"

  project_id = var.project_id

  labels = local.labels

  # Generated by Terraform. To change one, add a new version to the secret
  # rather than editing here: consumers read "latest", and Terraform keeps
  # managing only the version it created, so the two do not fight.
  #
  # The exception is the salt key. It encrypts provider credentials stored in
  # Postgres, so a new version makes every model already registered unreadable.
  secrets = {
    "${local.name}-db-password"        = module.cloud_sql.user_password
    "${local.name}-litellm-master-key" = "sk-${random_password.litellm_master_key.result}"
    "${local.name}-litellm-salt-key"   = random_password.litellm_salt_key.result

    "${local.name}-redis-password" = module.memorystore.auth_string

    # "sk-" because LiteLLM sends these as OpenAI-style bearer tokens.
    "${local.name}-vllm-api-key"      = "sk-${random_password.vllm_api_key.result}"
    "${local.name}-embedding-api-key" = "sk-${random_password.embedding_api_key.result}"

    "${local.name}-langfuse-secret" = random_password.langfuse_secret.result
  }

  # Deliberately no composed DATABASE_URL. Interpolating the sensitive password
  # together with the instance's IP — unknown until apply — makes secret_data
  # both sensitive and unknown at plan time, which the provider rejects with
  # "inconsistent values for sensitive attribute". The chart takes the host,
  # database name, and credentials as separate values anyway; see the
  # database_host / database_user outputs.

  # Created empty, because these are issued by someone else and cannot be
  # generated: a Tailscale auth key and a Hugging Face token.
  placeholder_secrets = [for s in var.placeholder_secrets : "${local.name}-${s}"]

  accessor_members = [module.litellm_service_account.member]

  depends_on = [module.project_services]
}

module "load_balancer" {
  source = "./modules/load-balancer"

  project_id          = var.project_id
  name                = "${local.name}-litellm"
  domain              = var.domain
  use_wildcard_dns    = var.use_wildcard_dns
  wildcard_dns_suffix = var.wildcard_dns_suffix

  depends_on = [module.project_services]
}
