locals {
  name = "${var.name_prefix}-${var.env}"

  labels = {
    env     = var.env
    project = var.name_prefix
  }
}

module "project_services" {
  source = "./modules/project-services"

  project_id = var.project_id
  services = [
    "compute.googleapis.com",
    "container.googleapis.com",
    "sqladmin.googleapis.com",
    "secretmanager.googleapis.com",
    "iam.googleapis.com",
    "iamcredentials.googleapis.com",
    "artifactregistry.googleapis.com",
  ]
}

module "network" {
  source = "./modules/network"

  name   = local.name
  region = var.region

  depends_on = [module.project_services]
}

# Least privilege for nodes, instead of the default Compute Engine account.
module "node_service_account" {
  source = "./modules/service-account"

  project_id   = var.project_id
  account_id   = "${local.name}-gke-node"
  display_name = "GKE node pool"
  # Registry access is granted per-repository below, not project-wide.
  project_roles = [
    "roles/logging.logWriter",
    "roles/monitoring.metricWriter",
    "roles/monitoring.viewer",
  ]

  depends_on = [module.project_services]
}

module "artifact_registry" {
  source = "./modules/artifact-registry"

  project_id    = var.project_id
  location      = var.region
  repository_id = local.name
  description   = "Container images for ${local.name}"
  format        = "DOCKER"
  labels        = local.labels

  readers = [module.node_service_account.member]

  depends_on = [module.project_services]
}

module "gke" {
  source = "./modules/gke"

  project_id = var.project_id
  name       = local.name
  location   = var.zone # zonal: one free cluster per billing account

  network_id          = module.network.network_id
  subnet_id           = module.network.subnet_id
  pods_range_name     = module.network.pods_range_name
  services_range_name = module.network.services_range_name

  node_service_account    = module.node_service_account.email
  master_authorized_cidrs = var.master_authorized_cidrs
  machine_type            = var.node_machine_type
  node_count              = var.node_count
  node_labels             = local.labels
}

module "cloud_sql" {
  source = "./modules/cloud-sql"

  project_id = var.project_id
  name       = local.name
  region     = var.region
  tier       = var.db_tier
  databases  = ["litellm", "langfuse"]
  user_name  = "litellm"

  depends_on = [module.project_services]
}

# LiteLLM reaches Cloud SQL through the Auth Proxy sidecar, authenticating as
# this account via Workload Identity. No key file is ever created.
module "litellm_service_account" {
  source = "./modules/service-account"

  project_id    = var.project_id
  account_id    = "${local.name}-litellm"
  display_name  = "LiteLLM gateway"
  project_roles = ["roles/cloudsql.client"]

  workload_identity_users = ["${var.litellm_namespace}/${var.litellm_ksa}"]

  depends_on = [module.project_services]
}

resource "random_password" "litellm_master_key" {
  length  = 40
  special = false
}

resource "random_password" "litellm_salt_key" {
  length  = 40
  special = false
}

module "secrets" {
  source = "./modules/secrets"

  project_id = var.project_id

  labels = local.labels

  # Generated by Terraform.
  secrets = {
    "${local.name}-db-password"        = module.cloud_sql.user_password
    "${local.name}-litellm-master-key" = "sk-${random_password.litellm_master_key.result}"
    "${local.name}-litellm-salt-key"   = random_password.litellm_salt_key.result

    # The Auth Proxy sidecar listens on localhost, so LiteLLM connects there.
    "${local.name}-database-url" = format(
      "postgresql://%s:%s@127.0.0.1:5432/litellm",
      module.cloud_sql.user_name,
      module.cloud_sql.user_password,
    )
  }

  # Created empty. Values are issued elsewhere and added by hand.
  placeholder_secrets = [for s in var.placeholder_secrets : "${local.name}-${s}"]

  accessor_members = [module.litellm_service_account.member]

  depends_on = [module.project_services]
}

module "load_balancer" {
  source = "./modules/load-balancer"

  project_id          = var.project_id
  name                = "${local.name}-litellm"
  domain              = var.domain
  use_wildcard_dns    = var.use_wildcard_dns
  wildcard_dns_suffix = var.wildcard_dns_suffix

  depends_on = [module.project_services]
}
